name: multi-steps

on:
  push:
    branches:
      - main
      - 'releases/**'

  pull_request:
    types: [opened, synchronize]

  issues:
    types:
      - opened
      - labeled

  workflow_dispatch:

jobs:
  build:
    name: run-multi-steps

    runs-on: windows-latest

    steps:
      - name: Checkout code from workspace
        if: github.actor == 'Mandeepsheoran'
        uses: actions/checkout@v2
        timeout-minutes: 10
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        timeout-minutes: 10
        with:
          java-version: 17

      - name: Run test
        timeout-minutes: 10
        shell: powershell
        run: |
         mvn -v 
         mvn clean test 
